package org.coursera.camppotlatch.service.model;

import java.util.Date;

import org.coursera.camppotlatch.service.json.DateJsonDeserializer;
import org.coursera.camppotlatch.service.json.DateJsonSerializer;
import org.coursera.camppotlatch.service.repository.DateTypeConverter;
import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.S3Link;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.base.Objects;
import com.google.gson.annotations.Expose;

@DynamoDBTable(tableName = "CampPotlach-Gifts")
public class Gift {
	
	public static final String CREATOR_LOGIN_INDEX = "creatorLogin-index";
	public static final String CAPTION_GIFT_ID_INDEX = "captionGiftId-index";
	
	public static final int THUMBNAIL_WIDTH = 240;
	public static final int THUMBNAIL_HEIGHT = 135;
	
	@Expose
	private String id;
	@Expose	
	private String title;
	
	@Expose
	private String imageId;
	
	private String imageContentType;
	private String imagePath;
	private S3Link imageS3Link;
	
	@Expose
	private String comments;
	@Expose
	private String creatorLogin;
	@Expose
	private Date createTime;
	@Expose
	private Integer likesCount;
	@Expose
	private Integer inappropriateCount;
	@Expose
	private String captionGiftId;

	@Expose	
	private String creatorName;
	@Expose	
	private Integer relatedCount;
	@Expose	
	private Integer likeFlag;
	@Expose	
	private Integer inappropriateFlag;
	
	private Long version;
	
	public Gift() {
		this(null, null, null, 
				null, null, null,
				0, 0,
				0, 0,
				0, null);
	}
	
	public Gift(String title, String imageId, String comments, 
			String creatorLogin, String creatorName, Date createTime, 
			Integer likesCount, Integer likeFlag, 
			Integer inappropriateCount, Integer inappropriateFlag, 
			Integer relatedCount, String captionGiftId) {
		this.title = title;
		this.imageId = imageId;
		this.comments = comments;
		this.creatorLogin = creatorLogin;
		this.creatorName = creatorName;
		this.createTime = createTime;
		this.likesCount = likesCount;
		this.likeFlag = likeFlag;
		this.inappropriateCount = inappropriateCount;
		this.inappropriateFlag = inappropriateFlag;
		this.relatedCount = relatedCount;
		this.captionGiftId = captionGiftId;
	}
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}

	@DynamoDBAttribute	
	public String getImageId() {
		return imageId;
	}
	public void setImageId(String imageId) {
		this.imageId = imageId;
	}
	
	@JsonIgnore
	@DynamoDBAttribute
	public String getImageContentType() {
		return imageContentType;
	}
	public void setImageContentType(String imageContentType) {
		this.imageContentType = imageContentType;
	}

	@JsonIgnore
	@DynamoDBIgnore
	public String getImagePath() {
		return imagePath;
	}
	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@JsonIgnore
	@DynamoDBAttribute
	public S3Link getImageS3Link() {
		return imageS3Link;
	}
	public void setImageS3Link(S3Link imageS3Link) {
		this.imageS3Link = imageS3Link; 
	}
	
	@DynamoDBAttribute
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	
	@DynamoDBAttribute
	@DynamoDBIndexHashKey(globalSecondaryIndexName=CREATOR_LOGIN_INDEX)
	public String getCreatorLogin() {
		return creatorLogin;
	}
	public void setCreatorLogin(String creatorLogin) {
		this.creatorLogin = creatorLogin;
	}
	
	@DynamoDBAttribute
	//@DynamoDBIndexRangeKey(globalSecondaryIndexNames={CREATOR_LOGIN_CREATE_TIME_INDEX, CAPTION_GIFT_ID_CREATE_TIME_INDEX})
	@DynamoDBMarshalling(marshallerClass = DateTypeConverter.class)
	@JsonSerialize(using=DateJsonSerializer.class)
	@JsonDeserialize(using=DateJsonDeserializer.class)
	public Date getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	@DynamoDBAttribute
	public Integer getLikesCount() {
		return likesCount;
	}
	public void setLikesCount(Integer likesCount) {
		this.likesCount = likesCount;
	}
	
	@DynamoDBAttribute
	public Integer getInappropriateCount() {
		return inappropriateCount;
	}
	public void setInappropriateCount(Integer inappropriateCount) {
		this.inappropriateCount = inappropriateCount;
	}
	
	@DynamoDBAttribute
	@DynamoDBIndexHashKey(globalSecondaryIndexName=CAPTION_GIFT_ID_INDEX)
	public String getCaptionGiftId() {
		return captionGiftId;
	}
	public void setCaptionGiftId(String captionGiftId) {
		this.captionGiftId = captionGiftId;
	}

	@DynamoDBAttribute
	public String getCreatorName() {
		return creatorName;
	}
	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}

	@DynamoDBAttribute
	public Integer getRelatedCount() {
		return relatedCount;
	}
	public void setRelatedCount(Integer relatedCount) {
		this.relatedCount = relatedCount;
	}

	@DynamoDBIgnore
	public Integer getLikeFlag() {
		return likeFlag;
	}
	public void setLikeFlag(Integer likeFlag) {
		this.likeFlag = likeFlag;
	}
	
	@DynamoDBIgnore
	public Integer getInappropriateFlag() {
		return inappropriateFlag;
	}
	public void setInappropriateFlag(Integer inappropriateFlag) {
		this.inappropriateFlag = inappropriateFlag;
	}
	
	@JsonIgnore
	@DynamoDBVersionAttribute
	public Long getVersion() {
		return version;
	}
	public void setVersion(Long version) {
		this.version = version;
	}
	
	/**
	 * Two Gifts will generate the same hashcode if they have exactly the same
	 * values for their title and url.
	 * 
	 */
	@Override
	public int hashCode() {
		// Google Guava provides great utilities for hashing
		return Objects.hashCode(title, creatorLogin, createTime);
	}

	/**
	 * Two Gifts are considered equal if they have exactly the same values for
	 * their title, url.
	 * 
	 */
	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Gift) {
			Gift other = (Gift) obj;
			// Google Guava provides great utilities for equals too!
			return Objects.equal(title, other.title)
					&& Objects.equal(creatorLogin, other.creatorLogin)
					&& Objects.equal(createTime, other.createTime);
		} else {
			return false;
		}
	}
}
